<?php

// --- PROBLEM ---
// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

$currentSum = 2;

$combinedTerm = 0;
$oldTerm = 1;
$newTerm = 2;
while($combinedTerm < 4000000) {
    $combinedTerm = $oldTerm + $newTerm;

    if ($combinedTerm % 2 == 0) {
        $currentSum += $combinedTerm;
    }

    $oldTerm = $newTerm;
    $newTerm = $combinedTerm;
}

echo $currentSum;
